version: '3.8'

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GPG_PRIVATE_KEY=${GPG_PRIVATE_KEY}
      - GPG_FINGERPRINT=${GPG_FINGERPRINT}
      - PASSPHRASE=${PASSPHRASE}
    volumes:
      - ..:/app
    working_dir: /app
    command: /bin/sh

volumes:
  go-cache:
  build-cache: